package com.example.administrator.notebook.function.writingFunction;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.notebook.function.writingFunction.WritingBean;
import com.example.administrator.notebook.function.planFunction.PlanBean;

import com.example.administrator.notebook.function.writingFunction.WritingBeanDao;
import com.example.administrator.notebook.function.planFunction.PlanBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig writingBeanDaoConfig;
    private final DaoConfig planBeanDaoConfig;

    private final WritingBeanDao writingBeanDao;
    private final PlanBeanDao planBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        writingBeanDaoConfig = daoConfigMap.get(WritingBeanDao.class).clone();
        writingBeanDaoConfig.initIdentityScope(type);

        planBeanDaoConfig = daoConfigMap.get(PlanBeanDao.class).clone();
        planBeanDaoConfig.initIdentityScope(type);

        writingBeanDao = new WritingBeanDao(writingBeanDaoConfig, this);
        planBeanDao = new PlanBeanDao(planBeanDaoConfig, this);

        registerDao(WritingBean.class, writingBeanDao);
        registerDao(PlanBean.class, planBeanDao);
    }
    
    public void clear() {
        writingBeanDaoConfig.clearIdentityScope();
        planBeanDaoConfig.clearIdentityScope();
    }

    public WritingBeanDao getWritingBeanDao() {
        return writingBeanDao;
    }

    public PlanBeanDao getPlanBeanDao() {
        return planBeanDao;
    }

}
